[DS to LF] Palette warning, error, success
LuccaSA/lucca-front pull request #1376
Opened 2021-05-28 13:30 UTC by BertrandPodevin

fix for https://github.com/LuccaSA/lucca-front/issues/1329

2021-05-28 13:32 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1376

2021-06-14 13:48 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1376

2021-06-15 15:28 UTC, sanlucca approved these changes

2021-06-15 15:29 UTC, sanlucca requested changes
Leave the default primary and secondary to its "grey" state

2021-06-16 08:05 UTC, closed without merging