[DS to LF][1348] Callout
LuccaSA/lucca-front pull request #1381
Opened 2021-05-28 15:00 UTC by RipripKipkip

2021-05-28 15:02 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1381

2021-06-02 12:43 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1381

2021-06-03 14:36 UTC, vvalentin-lucca commented on packages/scss/src/components/_callout.scss
> +	border: 1px solid _color($palette, 200);
theme divider

2021-06-03 14:36 UTC, vvalentin-lucca commented on packages/scss/src/theming/components/_callout.theme.scss
> +  background: _color("grey", "100")
background-color

2021-06-03 14:36 UTC, vvalentin-lucca commented on stories/qa/callout/callout.stories.ts
> +			default: 'toto',
?

2021-06-04 08:39 UTC, RipripKipkip commented on stories/qa/callout/callout.stories.ts
> +			default: 'toto',
ah j'avais fait ça pour avoir un fond blanc je vais enlever

2021-06-04 08:43 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1381

2021-06-29 16:27 UTC, sanlucca requested changes
Don't change the variable name (you can let the change on the css property)

2021-06-30 08:32 UTC, LuccaIntegration commented
jenkins auto deploy http://lucca-front.lucca.local/PR-1381

2021-07-01 13:20 UTC, sanlucca approved these changes

2021-07-05 07:55 UTC, merged

2021-07-05 07:56 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1381