nolog(sb) add scss/breadcrumbs story
LuccaSA/lucca-front pull request #1411
Opened 2021-07-23 13:50 UTC by MarcFairbrother

![image](https://user-images.githubusercontent.com/5755913/126791660-870e14d4-8f10-4f5a-b6c0-19a533e163b0.png)

2021-07-23 13:53 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1411

2021-07-23 15:18 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1411

2021-07-26 12:13 UTC, RipripKipkip approved these changes

2021-07-29 09:39 UTC, shajz requested changes
Vaut mieux ne pas mettre les href sur les liens, sinon la nav storybook est cassée cf https://github.com/LuccaSA/lucca-front/pull/1405

2021-07-29 09:39 UTC, shajz commented on stories/scss/breadcrumb/breadcrumb-basic.stories.html
> +        <li class="breadcrumbs-list-item"><a href="#" class="breadcrumbs-list-item-action">{{link}}</a></li>
```suggestion
        <li class="breadcrumbs-list-item"><a class="breadcrumbs-list-item-action">{{link}}</a></li>
```

2021-07-29 12:58 UTC, shajz approved these changes

2021-07-29 12:59 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1411

2021-07-29 13:01 UTC, merged