nolog(sb) add scss/labels story
LuccaSA/lucca-front pull request #1418
Opened 2021-07-26 09:33 UTC by AlexiaAlarza

![Capture d’écran 2021-07-26 à 11 33 36](https://user-images.githubusercontent.com/77682210/126967464-8b956c05-0301-4ee5-9c0a-e6a780d4dc23.png)

2021-07-26 09:38 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1418

2021-07-26 09:43 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1418

2021-07-26 14:17 UTC, RipripKipkip approved these changes

2021-07-29 09:36 UTC, shajz requested changes

2021-07-29 09:36 UTC, shajz commented on stories/scss/labels/label-basic.stories.ts
> +	@Input() mod: string = '';
Inutilisé, on peut le retirer (je me demandais à quoi servait la chaîne vide :D)

![image](https://user-images.githubusercontent.com/2089620/127469095-b5f2be00-b5f5-4116-918e-6d8a83fef2b9.png)

2021-07-29 12:50 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1418

2021-07-29 12:58 UTC, shajz approved these changes

2021-07-29 12:59 UTC, merged