nolog(sb) add scss/pageHeader story
LuccaSA/lucca-front pull request #1420
Opened 2021-07-27 09:15 UTC by AlexiaAlarza

![Capture d’écran 2021-07-27 à 11 14 33](https://user-images.githubusercontent.com/77682210/127128886-a664fffd-cd44-49e6-b3ae-8b3d8bee10b9.png)

2021-07-27 09:17 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1420

2021-07-29 07:45 UTC, MarcFairbrother commented on stories/scss/page-header/page-header-basic.stories.html
> +				<button class="button mod-outline mod-icon">
`type="button"`

2021-07-29 07:48 UTC, MarcFairbrother approved these changes

2021-07-29 07:52 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1420

2021-07-29 09:41 UTC, shajz requested changes
Pareil que https://github.com/LuccaSA/lucca-front/pull/1405

2021-07-29 09:41 UTC, shajz commented on stories/scss/page-header/page-header-basic.stories.html
> +				<li class="breadcrumbs-list-item"><a href="#" class="breadcrumbs-list-item-action">Are</a></li>
```suggestion
				<li class="breadcrumbs-list-item"><a class="breadcrumbs-list-item-action">You</a></li>
				<li class="breadcrumbs-list-item"><a class="breadcrumbs-list-item-action">Are</a></li>
```

2021-07-29 09:41 UTC, shajz commented on stories/scss/page-header/page-header-basic.stories.html
> +				<a target="_blank" href="#">Lien<span aria-hidden="true" class="lucca-icon icon-outside size-smaller u-marginLeftSmallest"></span></a>.
```suggestion
				<a target="_blank">Lien<span aria-hidden="true" class="lucca-icon icon-outside size-smaller u-marginLeftSmallest"></span></a>.
```

2021-07-29 09:41 UTC, shajz commented on stories/scss/page-header/page-header-basic.stories.html
> +			<a href="" class="menu-link"> tab </a>
```suggestion
			<a class="menu-link is-active"> tab </a>
			<a class="menu-link"> tab </a>
			<a class="menu-link"> tab </a>
			<a class="menu-link"> tab </a>
			<a class="menu-link"> tab </a>
			<a class="menu-link"> tab </a>
			<a class="menu-link"> tab </a>
```

2021-07-29 13:08 UTC, shajz approved these changes

2021-07-29 13:10 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1420

2021-07-29 13:32 UTC, merged