feat(scss) buttons mod-text
LuccaSA/lucca-front pull request #1435
Opened 2021-08-20 14:10 UTC by almonais

fix #1337

2021-08-20 14:12 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2021-08-20 14:14 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2021-08-20 14:26 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2021-08-24 15:21 UTC, MarcFairbrother submitted a review, later dismissed

2021-08-31 15:23 UTC, AlexiaAlarza reviewed
il faudrait peut être rajouter aussi l'icône pour voir comment ça se comporte ?

2021-08-31 15:23 UTC, AlexiaAlarza commented on packages/scss/src/components/_button.scss
> +			box-shadow: 0 2px 8px rgba(19, 29, 53, .04), 0 1px 2px rgba(19, 29, 53, .06), 0 0 0 4px _color($activeShadowPalette, "100"), inset 0 0 0 1px _color($activeShadowPalette, "400");
```suggestion
			box-shadow: _theme('commons.box-shadow.xs'), 0 0 0 4px _color($activeShadowPalette, "100"), inset 0 0 0 1px _color($activeShadowPalette, "400");
```

2021-08-31 15:23 UTC, AlexiaAlarza commented on packages/scss/src/components/_button.scss
> +		background-color: _color($palette, "50");
```suggestion
		background-color: _color($palette, "50");
		box-shadow: none;
```

Car sinon il prend le box-shadow par défaut du button:hover

2021-09-10 13:02 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2021-12-31 15:55 UTC, MarcFairbrother commented on packages/scss/src/components/_button.scss
> +	&.mod-link,
```suggestion
	&.mod-link, // legacy
```

2022-01-03 10:42 UTC, MarcFairbrother submitted a review, later dismissed

2022-01-04 15:42 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-02-21 13:44 UTC, AlexiaAlarza commented
@almonais dans la stories scss il faudrait modifier le mod-link par le mod-text du coup ;)

2022-03-02 16:12 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-04-15 15:03 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-04-21 09:04 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-04-21 09:17 UTC, jeremie-lucca requested changes

2022-04-21 09:17 UTC, jeremie-lucca commented on packages/scss/src/components/_button.scss
> +		&:active {
Can we have it inside the focus and the active declaration instead of having focus and active declared two times? (Easier for readers)

2022-04-21 09:17 UTC, jeremie-lucca commented on packages/scss/src/components/_button.scss
> +		&:not([disabled]) {
Do we also need is-disabled ?

2022-04-21 09:17 UTC, jeremie-lucca commented on packages/scss/src/components/_button.scss
> +				&:not([disabled]) {
Do we also need is-disabled ?

2022-04-21 09:17 UTC, jeremie-lucca commented on packages/scss/src/components/_button.scss
> +				@include buttonLinkColoring($name, $name);
Why do we have $name two times? 🤔

2022-04-21 09:23 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-04-29 14:16 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1435

2022-04-29 14:24 UTC, shajz approved these changes

2022-04-29 14:38 UTC, merged