[ADD] Select advanced stories
LuccaSA/lucca-front pull request #1801
Opened 2022-08-03 16:06 UTC by MaximeGenevier

Ajout d'un story pour montrer un exemple de select advanced

2022-08-03 16:09 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-04 08:11 UTC, shajz approved these changes

2022-08-04 08:31 UTC, jeremie-lucca requested changes
There are two notable issues: 
- Search feature doesn't work
- If we have Select all / Unselect all buttons, it should be a multiple select with checkbox inside options

2022-08-04 14:32 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-04 14:35 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-05 08:49 UTC, shajz commented on stories/documentation/forms/select/select-advanced.stories.ts
> +			</ng-container>
missing luDisplayerMultiple (check the code we took inspiration from)

2022-08-08 15:49 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-08 16:04 UTC, shajz commented on stories/documentation/forms/select/select-advanced.stories.ts
> +			<ng-template luDisplayer let-colors luDisplayerMultiple="true">
```suggestion
			<ng-template luDisplayer let-colors [luDisplayerMultiple]="true">
```

2022-08-08 16:04 UTC, shajz commented on stories/documentation/forms/select/select-advanced.stories.ts
> +			<ng-template luDisplayer let-colors luDisplayerMultiple="true">
dito

2022-08-09 07:27 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-09 08:15 UTC, shajz submitted a review, later dismissed
@jeremie-lucca faut que tu approuves aussi

2022-08-09 13:52 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1801/storybook

2022-08-10 08:55 UTC, merged