Fix type search
LuccaSA/lucca-front pull request #1858
Opened 2022-09-15 12:28 UTC by vvalentin-lucca

Fix #1848

Remove clear action and search decoration.

2022-09-16 08:24 UTC, BertrandPodevin approved these changes

2022-09-21 14:55 UTC, jeremie-lucca requested changes

2022-09-21 14:55 UTC, jeremie-lucca commented on packages/scss/src/components/textfield/component.scss
> +			&[type="search] {
```suggestion
			&[type="search"] {
```

2022-09-21 15:02 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-1858/storybook

2022-09-30 12:11 UTC, jeremie-lucca approved these changes

2022-09-30 13:02 UTC, merged