Standalone Component For Stories
LuccaSA/lucca-front pull request #2043
Opened 2023-03-15 13:47 UTC by JeSuisCharlie1

## Description

Mise en place de chacune des stories en standalone component.

-----

Refacto des noms des stories/lint.

-----

2023-03-15 14:39 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-15 14:42 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-15 15:07 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-15 15:12 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-15 15:16 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-16 15:31 UTC, shajz commented
still in draft, some stories are broken

2023-03-21 14:06 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-23 17:03 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-03-24 09:01 UTC, GuillaumeNury approved these changes

2023-05-31 14:28 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-05-31 14:30 UTC, JeSuisCharlie1 commented
Le rebase c'est bien passer, je n’ai pas de soucis de particulier de mon côté je fais une petite batterie de test sur les stories.

2023-05-31 14:40 UTC, GuillaumeNury requested changes

2023-05-31 14:40 UTC, GuillaumeNury commented on stories/documentation/forms/date/select/date-select.stories.ts
> -import { FormsModule } from '@angular/forms';
Sur ce fichier, il faut garder ma version :)

2023-05-31 14:44 UTC, JeSuisCharlie1 commented
Ok merci je fais la modif 😄

2023-05-31 14:48 UTC, GuillaumeNury approved these changes

2023-05-31 14:50 UTC, LuccaIntegration commented
:woman_cook: http://lucca-front.lucca.local/PR-2043/storybook

2023-05-31 15:27 UTC, shajz approved these changes

2023-06-01 08:06 UTC, merged