fix(core-select/select-input): placeholder
LuccaSA/lucca-front pull request #2617
Opened 2024-02-29 15:25 UTC by LucasPerrault

## Description

fix select-input placeholder of core-select
-----

2024-02-29 15:28 UTC, Supamiu requested changes

2024-02-29 15:28 UTC, Supamiu commented on packages/ng/core-select/input/select-input.component.ts
> +		return this.value ? null : this.placeholder$.value;
Not a big fan of this, we should use `| async` in the template instead.

2024-02-29 15:38 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/13963/ui-diff)

2024-02-29 17:00 UTC, Supamiu approved these changes

2024-02-29 17:04 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2617/storybook

2024-02-29 17:09 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/13974/ui-diff)

2024-03-01 09:10 UTC, GuillaumeNury approved these changes

2024-03-01 09:14 UTC, merged