feat(checkbox): issue #2677 add mixed input
LuccaSA/lucca-front pull request #2679
Opened 2024-03-25 14:55 UTC by MaximeGenevier

## Description

Closes #2677 : add a `mixed` boolean input for checkbox-field component. 
When the input is `true`, the attribute `aria-check` is set to `mixed`.

-----
-----

2024-03-25 14:59 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2679/storybook

2024-03-25 15:11 UTC, Supamiu requested changes

2024-03-25 15:11 UTC, Supamiu commented on stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
> +		const { label, hiddenLabel, tooltip, inlineMessage, inlineMessageState, size, mixed, ...inputArgs } = args;
Keeping mixed in `inputArgs` makes more sense so it's handled as the boolean attribute it is would be better.

2024-03-25 15:11 UTC, Supamiu commented on stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
> +	[mixed]="${mixed}"/>
Removing this woule be better, as `generateInputs` will take care of that if you just let `mixed` in `inputArgs`.

2024-03-25 15:22 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/15092/ui-diff)

2024-03-25 19:31 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2679/storybook

2024-03-25 19:43 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/15111/ui-diff)

2024-03-26 13:32 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2679/storybook

2024-03-26 13:44 UTC, Supamiu approved these changes

2024-03-26 13:57 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/15158/ui-diff)

2024-03-26 16:07 UTC, merged