[Simple & Multi Select] Expose MAX_PAGE_SIZE and update doc.
LuccaSA/lucca-front pull request #2756
Opened 2024-04-23 15:56 UTC by Nurovek

## Description

Doc on how to override the user directive has been written in https://github.com/LuccaSA/lucca-front/pull/2748.
However, some explanation was missing, especially regarding the limit parameter which must be provided in the request, in order to trigger the page change on scroll.

This PR is meant to update the doc, as well as exposing the `MAX_PAGE_SIZE` const, which is a good default value if you don't want to provide a custom limit.

2024-04-24 11:39 UTC, GuillaumeNury approved these changes

2024-04-24 11:39 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2756/storybook

2024-04-24 11:40 UTC, GuillaumeNury requested changes

2024-04-24 11:40 UTC, GuillaumeNury commented on docs/core-select-users-directive.md
> +import { MAGIC_PAGE_SIZE } from '@lucca-front/ng/core-select/api';
En fait, il faudrait le renommer en `LU_SELECT_MAGIC_PAGE_SIZE `

2024-04-24 11:44 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/16424/ui-diff)

2024-04-24 11:51 UTC, Nurovek commented on docs/core-select-users-directive.md
> +import { MAGIC_PAGE_SIZE } from '@lucca-front/ng/core-select/api';
C'est fait 👍

2024-04-24 11:54 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2756/storybook

2024-04-24 11:58 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/16426/ui-diff)

2024-04-25 08:20 UTC, GuillaumeNury approved these changes

2024-04-25 08:20 UTC, merged