indexTable sortable
LuccaSA/lucca-front pull request #2858
Opened 2024-06-11 16:01 UTC by vvalentin-lucca

## Description

New design makes it possible to differentiate between sortable and non-sortable columns without having to fly over them.

-----

-----

![Capture d’écran 2024-06-11 à 17 52 45](https://github.com/LuccaSA/lucca-front/assets/64789527/50e07dfa-88de-43b1-b69d-0f72425bed80)

2024-06-11 16:14 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2858/storybook

2024-06-11 16:18 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/18244/ui-diff)

2024-06-12 07:12 UTC, fbasmaison-lucca commented on packages/scss/src/components/indexTableSorted/component.scss
> +    flex-direction: var(--components-sorted-direction);
Indentation is too large here (5-17).

2024-06-12 07:15 UTC, fbasmaison-lucca commented on packages/scss/src/components/indexTableSorted/component.scss
> +    flex-direction: var(--components-sorted-direction);
Actually, this file hesitate between 2 spaces and 4 spaces indentation.

(Maybe adding some tabs would be fun! :p)

2024-06-12 07:20 UTC, fbasmaison-lucca commented on packages/scss/src/components/indexTableSorted/vars.scss
> +    --components-sorted-offset: calc(var(--pr-t-spacings-50) * -1);
Inconsistent indentation here as well.

2024-06-12 07:34 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/18260/ui-diff)

2024-06-14 09:32 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2858/storybook

2024-06-14 09:36 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/18331/ui-diff)

2024-08-01 14:56 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2858/storybook

2024-08-01 15:00 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/21282/ui-diff)

2024-08-01 15:24 UTC, jeremie-lucca requested changes

2024-08-01 15:24 UTC, jeremie-lucca commented on packages/scss/src/components/tableSorted/component.scss
> +		.table-head-row-cell-sortableButton-arrows,
If we consider tableSorted as a component, maybe could replace `.table-head-row-cell-sortableButton` and `.indexTable-head-row-cell-sortableButton` basis by `.tableSortable` ?

2024-08-19 12:52 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2858/storybook

2024-08-19 12:56 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/21740/ui-diff)

2024-08-19 13:37 UTC, jeremie-lucca approved these changes

2024-08-19 13:40 UTC, merged