feat(comment): basic angular wrapper implementation
LuccaSA/lucca-front pull request #2866
Opened 2024-06-18 09:02 UTC by Supamiu

## Description

New comment component wrapper, this is a base implementation that's missing a lot of details inside its API:

- The component will need a `user` with at least `firstName`, `lastName` and an `id` for the employeePopover that we'll add in the future.
- We might want to be able to configure how comment's date is going to be formatted, this is not trivial and should be handled with caution in the API (have `DatePipe`'s format as param? Ask for the string rendering? What about locale?)
- HTML comment structure has some grouping logic, this should be handled in a parent component and needs further investigation imo.

Given that this wasn't really planned yet, it's more of a base implementation that needs improvements and that can be used as a base discussion element.

-----

-----

2024-06-18 09:09 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/18438/ui-diff)

2024-08-28 13:37 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-08-28 13:42 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/22155/ui-diff)

2024-08-30 08:45 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-08-30 08:49 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/22216/ui-diff)

2024-10-03 15:25 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-03 16:11 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-07 13:09 UTC, jeremie-lucca requested changes

2024-10-07 13:09 UTC, jeremie-lucca commented on packages/ng/comment/comment-chat/comment-chat.component.html
> +<ol class="commentWrapperChat">
I wonder if this shouldn't be considered as a new component as I heard Clément speaking about "Chatbox". I'll investigate.

2024-10-07 13:09 UTC, jeremie-lucca commented on packages/scss/src/components/comment/component.scss
> +	gap: var(--pr-t-spacings-100);
```suggestion
	gap: var(--pr-t-spacings-50);
```

2024-10-07 13:09 UTC, jeremie-lucca commented on packages/scss/src/components/comment/component.scss
> -				padding-left: var(--components-comment-content-margin);
Is there a reason behind this deletion? 
It seems to break the comment's wrap (with avatar only on first comment) :
![image](https://github.com/user-attachments/assets/bea05204-fde0-4ac2-ae6b-60db351fcdcf)

2024-10-07 13:30 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-07 13:34 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23622/ui-diff)

2024-10-07 13:37 UTC, jeremie-lucca commented
(Waiting design feedback on components naming before mergin')

2024-10-10 08:35 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-10 16:21 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-11 07:47 UTC, jeremie-lucca submitted a review, later dismissed

2024-10-11 07:54 UTC, jeremie-lucca approved these changes

2024-10-11 07:59 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-2866/storybook

2024-10-11 08:01 UTC, merged