Textarea autoResize
LuccaSA/lucca-front pull request #3062
Opened 2024-09-06 08:34 UTC by vvalentin-lucca

## Description

-----

-----

2024-09-06 08:38 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-06 08:41 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/22482/ui-diff)

2024-09-06 09:36 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/22486/ui-diff)

2024-09-25 16:06 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-25 16:10 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23226/ui-diff)

2024-09-26 08:57 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-26 09:01 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23240/ui-diff)

2024-09-26 09:09 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-26 09:10 UTC, Supamiu submitted a review, later dismissed

2024-09-26 09:11 UTC, GuillaumeNury requested changes

2024-09-26 09:11 UTC, GuillaumeNury commented on packages/ng/forms/textarea-input/textarea-input.component.ts
> +		this.#cdr.detectChanges();
Why this `detechChanges`? It should not be needed as `updateScroll` is called in an event binding.

2024-09-26 09:13 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23242/ui-diff)

2024-09-26 09:20 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-26 09:24 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23243/ui-diff)

2024-09-26 10:03 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-09-26 10:07 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23246/ui-diff)

2024-10-04 16:27 UTC, GuillaumeNury approved these changes
Could you add a comment explaining the `this.#cdr.detectChanges();` ?

2024-10-07 09:32 UTC, jeremie-lucca approved these changes

2024-10-07 09:35 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3062/storybook

2024-10-07 09:40 UTC, CCNET-iLucca commented
[Tests d'interfaces](https://qa.lucca.tech/23600/ui-diff)

2024-10-07 09:41 UTC, merged