refactor(select): do not override overlay container
LuccaSA/lucca-front pull request #3230
Opened 2024-11-22 08:59 UTC by LucasPerrault

WebComponents cannot used selects due to the overlay container override. 
We use the child to update overlay container properties and not the override.

## Description

Delete provideLuSelectOverlayContainer() and add attributes aria-labelledby & lu-select-overlay-container in the panel factory

-----

2024-11-22 09:12 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3230/storybook

2024-11-22 14:43 UTC, Supamiu submitted a review, later dismissed

2024-11-22 14:58 UTC, jeremie-lucca commented
It seems to break Select Multi's displayer 🥲
![image](https://github.com/user-attachments/assets/ee8ac124-7c12-4199-9b8d-6c7d247c0550)

2024-11-22 15:00 UTC, jeremie-lucca requested changes
It seems to break Select Multi's displayer 🥲
![image](https://github.com/user-attachments/assets/4a3c214f-3a14-4713-bcdf-3c5dfd937de6)

2024-11-26 10:29 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3230/storybook

2024-11-26 13:03 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3230/storybook

2024-12-06 13:42 UTC, jeremie-lucca commented
UI is fixed after the last commit. 
@Supamiu, @GuillaumeNury, everything's good on your side?

2024-12-06 14:38 UTC, Supamiu approved these changes

2024-12-06 15:10 UTC, LuccaIntegration commented
:woman_cook: https://lucca-front.lucca.tech/PR-3230/storybook

2024-12-06 16:10 UTC, merged